---
- name: Ensure dependencies are installed.
  apt:
    name:
      - python3-debian
    state: present

- name: Add Docker repository.
  deb822_repository:
    name: docker
    types: deb
    uris: "{{ docker_apt_repository }}"
    state: present
    suites: "{{ ansible_distribution_release }}"
    components: "{{docker_apt_release_channel }}"
    signed_by: "{{ docker_apt_gpg_key }}"
  register: docker_repository

- name: Update Apt cache if repositories have changed
  apt:
    update_cache: true
  when: docker_repository is changed
